CREATE DATABASE DRONE_DATABASE;
USE DRONE_DATABASE;

CREATE TABLE COORDINATES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idNum int,
X INT,
Y INT
);


CREATE TABLE COORDINATES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
X INT,
Y INT
);

CREATE TABLE PRODUCT(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
weightPerQuantity DOUBLE,
order_id INT,
CONSTRAINT FOREIGN KEY (order_id) REFERENCES ORDERS(id)
);

CREATE TABLE TableProducts(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity int,
product_id INT,
CONSTRAINT FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
supply bool,
delivered bool
);

CREATE TABLE ORDERS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
stringDate VARCHAR(255) NOT NULL,
battery INT,
model VARCHAR(255) NOT NULL,
quantity_id INT,
CONSTRAINT FOREIGN KEY (quantity_id) REFERENCES TableProducts(id)
);

CREATE TABLE DRONE_DELIVERY_WINDOWS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
battery INT,
start_time VARCHAR(255) NOT NULL,
end_timr VARCHAR(255) NOT NULL
);






