CREATE DATABASE DRONE_DATABASE;
USE DRONE_DATABASE;


CREATE TABLE COORDINATES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
X INT,
Y INT
);

CREATE TABLE PRODUCT(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
weightPerQuantity DOUBLE,
order_id INT,
CONSTRAINT FOREIGN KEY (order_id) REFERENCES ORDERS(id)
);

CREATE TABLE TableProducts(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity int,
product_id INT,

#CONSTRAINT FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
supply bool,
delivered bool
);

CREATE TABLE ORDERS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
stringDate VARCHAR(255) NOT NULL,
battery INT,
model VARCHAR(255) NOT NULL,
quantity_id INT,
CONSTRAINT FOREIGN KEY (quantity_id) REFERENCES TableProducts(id),
coordinates_id int,
CONSTRAINT FOREIGN KEY (coordinates_id) REFERENCES COORDINATES(id)
);

CREATE TABLE ORDERS_2(
orders_adds_id INT,
CONSTRAINT FOREIGN KEY (orders_adds_id) REFERENCES ORDERS_ADDS(id),
quantity_id INT,
CONSTRAINT FOREIGN KEY (quantity_id) REFERENCES TableProducts(id),
coordinates_id int,
CONSTRAINT FOREIGN KEY (coordinates_id) REFERENCES COORDINATES(id)
);

CREATE TABLE ORDERS_ADDS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
stringDate VARCHAR(255) NOT NULL,
battery INT,
model VARCHAR(255) NOT NULL
);

CREATE TABLE DRONE_DELIVERY_WINDOWS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
battery INT,
start_time VARCHAR(255) NOT NULL,
end_timr VARCHAR(255) NOT NULL
);

ALTER TABLE ORDERS_2
ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE DRONE_DELIVERY_WINDOWS
ADD id_drone INT NOT NULL;






